apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "spring-boot-rest-api"
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: "fabandalm/spring-boot-rest-api"
spec:
  type: service
  lifecycle: "unknown"
  owner: "unknown"
  providesApis:
    - "spring-boot-rest-api"
