site_name: "spring-boot-rest-api"
site_description: "address book api's doc"
docs_dir: backstage-docs

plugins:
  - techdocs-core

nav:
  - Overview:
    - What is it?: 'overview/overview.md'
  - Brief Description:
    - APIs: 'api-description/api-description.md'

