site_name: "spring-boot-rest-api"
site_description: "address book api's doc"
docs_dir: backstage-docs
repo_url: https://github.com/fabandalm/spring-boot-rest-api

nav:
  - Overview:
    - What is it?: 'overview.md'
  - Brief Description:
    - APIs: 'api-description.md'

plugins:
  - techdocs-core