site_name: "SpringBoot REST API"
site_description: "address book api's doc"
docs_dir: backstage-docs
repo_url: https://github.com/fabandalm/spring-boot-rest-api

plugins:
  - techdocs-core

nav:
  - Overview:
    - What is it?: 'overview/overview.md'
  - Brief Description:
    - APIs: 'api-description/api-description.md'

