site_name: "spring-boot-rest-api"
site_description: "address book api's doc"
docs_dir: backstage-docs

nav:
  - Overview:
    - What is it?: 'index.md'
  - Brief Description:
    - APIs: 'api-description.md'

plugins:
  - techdocs-core