apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: address-book
  description: The address-book API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/fabandalm/spring-boot-rest-api
      title: GitHub Repo
      icon: github
    - url: https://github.com/fabandalm/spring-boot-rest-api/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: ./openapi.yaml