apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: address-book
  description: The address-book API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/fabandalm/spring-boot-rest-api
      title: GitHub Repo
      icon: github
    - url: https://github.com/fabandalm/spring-boot-rest-api/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: |
    openapi: 3.0.1
    info:
      title: OpenAPI definition
      version: v0
    servers:
      - url: http://localhost:8080/api/v1
        description: Generated server url
    paths:
      /:
        get:
          tags:
            - address-book
          operationId: getAllContacts
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
        post:
          tags:
            - address-book
          operationId: addContact
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Contact'
            required: true
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/Contact'
      /{id}:
        get:
          tags:
            - address-book
          operationId: getContact
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: string
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/Contact'
    components:
      schemas:
        Contact:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            phone:
              type: string
